<a href="https://colab.research.google.com/github/sanusiahmad/paper/blob/main/latihan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import cv2
import math
import numpy as np

ori = cv2.imread('ss.jpg', cv2.IMREAD_UNCHANGED)

In [51]:
# Ubah colorspace gambar dari BGR ke HSV
converted = cv2.cvtColor(ori, cv2.COLOR_BGR2HSV)

In [52]:
# Contoh ingin mendeteksi warna biru
# maka pertama kita akan mencari threshold untuk warna biru
lowColor = np.array([100, 10, 10])
highColor = np.array([120, 255, 255])

In [53]:
#Buat masking dengan rentang warna yang akan dideteksi
masking = cv2.inRange(converted, lowColor, highColor)

In [54]:
#Erosi untuk menghilangkan noise pada gambar
masking = cv2.erode(masking, None, iterations=1)


In [55]:
#Cari Contours
contours, hierarchy = cv2.findContours(masking, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
print(len(contours))


591


In [56]:
#Hitung area contours
print(cv2.contourArea(contours[0]))

0.0


In [61]:
#Gambarkan contours
imgx = cv2.drawContours(ori, contours, -1, (0, 200, 0), 3)
print(imgx)

[[[  0 200   0]
  [  0 200   0]
  [  0 200   0]
  ...
  [  0 200   0]
  [  0 200   0]
  [  0 200   0]]

 [[  0 200   0]
  [  0 200   0]
  [  0 200   0]
  ...
  [  0 200   0]
  [  0 200   0]
  [  0 200   0]]

 [[  0 200   0]
  [  0 200   0]
  [  0 200   0]
  ...
  [  0 200   0]
  [  0 200   0]
  [  0 200   0]]

 ...

 [[197 196 198]
  [196 195 197]
  [197 196 198]
  ...
  [137 131 132]
  [137 131 132]
  [137 131 132]]

 [[186 185 187]
  [194 193 195]
  [203 202 204]
  ...
  [123 117 118]
  [123 117 118]
  [123 117 118]]

 [[177 176 178]
  [193 192 194]
  [209 208 210]
  ...
  [132 126 127]
  [132 126 127]
  [132 126 127]]]
